//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coming_goods: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _C__партии;
     public decimal C__партии 
     { 
      get
      {
       return _C__партии;
      } 
      set
      {
       if(_C__партии != value)
       {
        _C__партии = value;
        OnPropertyChanged("C__партии");
       }
      }
     }
     
        private string _Наименование;
     public string Наименование 
     { 
      get
      {
       return _Наименование;
      } 
      set
      {
       if(_Наименование != value)
       {
        _Наименование = value;
        OnPropertyChanged("Наименование");
       }
      }
     }
     
        private decimal _Тип;
     public decimal Тип 
     { 
      get
      {
       return _Тип;
      } 
      set
      {
       if(_Тип != value)
       {
        _Тип = value;
        OnPropertyChanged("Тип");
       }
      }
     }
     
        private decimal _Кол_во;
     public decimal Кол_во 
     { 
      get
      {
       return _Кол_во;
      } 
      set
      {
       if(_Кол_во != value)
       {
        _Кол_во = value;
        OnPropertyChanged("Кол_во");
       }
      }
     }
     
        private Nullable<System.DateTime> _Прибытие;
     public Nullable<System.DateTime> Прибытие 
     { 
      get
      {
       return _Прибытие;
      } 
      set
      {
       if(_Прибытие != value)
       {
        _Прибытие = value;
        OnPropertyChanged("Прибытие");
       }
      }
     }
     
    }
}
