//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_goods: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _id_invoice;
     public decimal id_invoice 
     { 
      get
      {
       return _id_invoice;
      } 
      set
      {
       if(_id_invoice != value)
       {
        _id_invoice = value;
        OnPropertyChanged("id_invoice");
       }
      }
     }
     
        private string _brand;
     public string brand 
     { 
      get
      {
       return _brand;
      } 
      set
      {
       if(_brand != value)
       {
        _brand = value;
        OnPropertyChanged("brand");
       }
      }
     }
     
        private decimal _count;
     public decimal count 
     { 
      get
      {
       return _count;
      } 
      set
      {
       if(_count != value)
       {
        _count = value;
        OnPropertyChanged("count");
       }
      }
     }
     
        private decimal _price;
     public decimal price 
     { 
      get
      {
       return _price;
      } 
      set
      {
       if(_price != value)
       {
        _price = value;
        OnPropertyChanged("price");
       }
      }
     }
     
        private decimal _cost;
     public decimal cost 
     { 
      get
      {
       return _cost;
      } 
      set
      {
       if(_cost != value)
       {
        _cost = value;
        OnPropertyChanged("cost");
       }
      }
     }
     
        private decimal _margin;
     public decimal margin 
     { 
      get
      {
       return _margin;
      } 
      set
      {
       if(_margin != value)
       {
        _margin = value;
        OnPropertyChanged("margin");
       }
      }
     }
     
    }
}
