//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseEntities : DbContext
    {
        public WarehouseEntities()
            : base("name=WarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Merchandise> Merchandise { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<User_Inf> User_Inf { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Worktype> Worktype { get; set; }
        public virtual DbSet<Send> Send { get; set; }
        public virtual DbSet<Users_inv> Users_inv { get; set; }
        public virtual DbSet<Coming_goods> Coming_goods { get; set; }
        public virtual DbSet<Goods_in_type> Goods_in_type { get; set; }
        public virtual DbSet<Invoice_goods> Invoice_goods { get; set; }
        public virtual DbSet<Not_issued_goods> Not_issued_goods { get; set; }
        public virtual DbSet<Product_to_sell> Product_to_sell { get; set; }
        public virtual DbSet<Search_coming_goods> Search_coming_goods { get; set; }
        public virtual DbSet<Search_contractors> Search_contractors { get; set; }
        public virtual DbSet<Search_goods_brand> Search_goods_brand { get; set; }
        public virtual DbSet<View_invoice> View_invoice { get; set; }
        public virtual DbSet<View_margin> View_margin { get; set; }
        public virtual DbSet<View_merch> View_merch { get; set; }
        public virtual DbSet<View_send_goods> View_send_goods { get; set; }
    }
}
