//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        public Order()
        {
            this.Merchandise = new HashSet<Merchandise>();
        }
    
        private decimal _consigment;
     public decimal consigment 
     { 
      get
      {
       return _consigment;
      } 
      set
      {
       if(_consigment != value)
       {
        _consigment = value;
        OnPropertyChanged("consigment");
       }
      }
     }
     
        private decimal _id_contractor;
     public decimal id_contractor 
     { 
      get
      {
       return _id_contractor;
      } 
      set
      {
       if(_id_contractor != value)
       {
        _id_contractor = value;
        OnPropertyChanged("id_contractor");
       }
      }
     }
     
        private Nullable<decimal> _summ;
     public Nullable<decimal> summ 
     { 
      get
      {
       return _summ;
      } 
      set
      {
       if(_summ != value)
       {
        _summ = value;
        OnPropertyChanged("summ");
       }
      }
     }
     
        private Nullable<System.DateTime> _date_order;
     public Nullable<System.DateTime> date_order 
     { 
      get
      {
       return _date_order;
      } 
      set
      {
       if(_date_order != value)
       {
        _date_order = value;
        OnPropertyChanged("date_order");
       }
      }
     }
     
        private Nullable<System.DateTime> _date_import;
     public Nullable<System.DateTime> date_import 
     { 
      get
      {
       return _date_import;
      } 
      set
      {
       if(_date_import != value)
       {
        _date_import = value;
        OnPropertyChanged("date_import");
       }
      }
     }
     
        private decimal _id_user;
     public decimal id_user 
     { 
      get
      {
       return _id_user;
      } 
      set
      {
       if(_id_user != value)
       {
        _id_user = value;
        OnPropertyChanged("id_user");
       }
      }
     }
     
    
        private Contractor _Contractor;
     public virtual Contractor Contractor 
     { 
      get
      {
       return _Contractor;
      } 
      set
      {
       if(_Contractor != value)
       {
        _Contractor = value;
        OnPropertyChanged("Contractor");
       }
      }
     }
     
        private ICollection<Merchandise> _Merchandise;
     public virtual ICollection<Merchandise> Merchandise 
     { 
      get
      {
       return _Merchandise;
      } 
      set
      {
       if(_Merchandise != value)
       {
        _Merchandise = value;
        OnPropertyChanged("Merchandise");
       }
      }
     }
     
        private Users _Users;
     public virtual Users Users 
     { 
      get
      {
       return _Users;
      } 
      set
      {
       if(_Users != value)
       {
        _Users = value;
        OnPropertyChanged("Users");
       }
      }
     }
     
    }
}
