//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_to_sell: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _id_merch;
     public decimal id_merch 
     { 
      get
      {
       return _id_merch;
      } 
      set
      {
       if(_id_merch != value)
       {
        _id_merch = value;
        OnPropertyChanged("id_merch");
       }
      }
     }
     
        private string _Наименование;
     public string Наименование 
     { 
      get
      {
       return _Наименование;
      } 
      set
      {
       if(_Наименование != value)
       {
        _Наименование = value;
        OnPropertyChanged("Наименование");
       }
      }
     }
     
        private string _name;
     public string name 
     { 
      get
      {
       return _name;
      } 
      set
      {
       if(_name != value)
       {
        _name = value;
        OnPropertyChanged("name");
       }
      }
     }
     
        private decimal _C__партии;
     public decimal C__партии 
     { 
      get
      {
       return _C__партии;
      } 
      set
      {
       if(_C__партии != value)
       {
        _C__партии = value;
        OnPropertyChanged("C__партии");
       }
      }
     }
     
        private Nullable<decimal> _Кол_во;
     public Nullable<decimal> Кол_во 
     { 
      get
      {
       return _Кол_во;
      } 
      set
      {
       if(_Кол_во != value)
       {
        _Кол_во = value;
        OnPropertyChanged("Кол_во");
       }
      }
     }
     
        private Nullable<decimal> _Цена;
     public Nullable<decimal> Цена 
     { 
      get
      {
       return _Цена;
      } 
      set
      {
       if(_Цена != value)
       {
        _Цена = value;
        OnPropertyChanged("Цена");
       }
      }
     }
     
    }
}
