//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        public Role()
        {
            this.Users = new HashSet<Users>();
        }
    
        private decimal _id_role;
     public decimal id_role 
     { 
      get
      {
       return _id_role;
      } 
      set
      {
       if(_id_role != value)
       {
        _id_role = value;
        OnPropertyChanged("id_role");
       }
      }
     }
     
        private string _name;
     public string name 
     { 
      get
      {
       return _name;
      } 
      set
      {
       if(_name != value)
       {
        _name = value;
        OnPropertyChanged("name");
       }
      }
     }
     
    
        private ICollection<Users> _Users;
     public virtual ICollection<Users> Users 
     { 
      get
      {
       return _Users;
      } 
      set
      {
       if(_Users != value)
       {
        _Users = value;
        OnPropertyChanged("Users");
       }
      }
     }
     
    }
}
