//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search_contractors: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private string _Фамилия;
     public string Фамилия 
     { 
      get
      {
       return _Фамилия;
      } 
      set
      {
       if(_Фамилия != value)
       {
        _Фамилия = value;
        OnPropertyChanged("Фамилия");
       }
      }
     }
     
        private string _Имя;
     public string Имя 
     { 
      get
      {
       return _Имя;
      } 
      set
      {
       if(_Имя != value)
       {
        _Имя = value;
        OnPropertyChanged("Имя");
       }
      }
     }
     
        private string _Отчество;
     public string Отчество 
     { 
      get
      {
       return _Отчество;
      } 
      set
      {
       if(_Отчество != value)
       {
        _Отчество = value;
        OnPropertyChanged("Отчество");
       }
      }
     }
     
        private string _Физический_адрес;
     public string Физический_адрес 
     { 
      get
      {
       return _Физический_адрес;
      } 
      set
      {
       if(_Физический_адрес != value)
       {
        _Физический_адрес = value;
        OnPropertyChanged("Физический_адрес");
       }
      }
     }
     
        private string _Юридический_адрес;
     public string Юридический_адрес 
     { 
      get
      {
       return _Юридический_адрес;
      } 
      set
      {
       if(_Юридический_адрес != value)
       {
        _Юридический_адрес = value;
        OnPropertyChanged("Юридический_адрес");
       }
      }
     }
     
        private decimal _ИНН;
     public decimal ИНН 
     { 
      get
      {
       return _ИНН;
      } 
      set
      {
       if(_ИНН != value)
       {
        _ИНН = value;
        OnPropertyChanged("ИНН");
       }
      }
     }
     
        private string _Телефоны;
     public string Телефоны 
     { 
      get
      {
       return _Телефоны;
      } 
      set
      {
       if(_Телефоны != value)
       {
        _Телефоны = value;
        OnPropertyChanged("Телефоны");
       }
      }
     }
     
    }
}
