//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search_coming_goods: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _id_merch;
     public decimal id_merch 
     { 
      get
      {
       return _id_merch;
      } 
      set
      {
       if(_id_merch != value)
       {
        _id_merch = value;
        OnPropertyChanged("id_merch");
       }
      }
     }
     
        private string _brand;
     public string brand 
     { 
      get
      {
       return _brand;
      } 
      set
      {
       if(_brand != value)
       {
        _brand = value;
        OnPropertyChanged("brand");
       }
      }
     }
     
        private string _name;
     public string name 
     { 
      get
      {
       return _name;
      } 
      set
      {
       if(_name != value)
       {
        _name = value;
        OnPropertyChanged("name");
       }
      }
     }
     
        private decimal _count_order;
     public decimal count_order 
     { 
      get
      {
       return _count_order;
      } 
      set
      {
       if(_count_order != value)
       {
        _count_order = value;
        OnPropertyChanged("count_order");
       }
      }
     }
     
        private bool _arrived;
     public bool arrived 
     { 
      get
      {
       return _arrived;
      } 
      set
      {
       if(_arrived != value)
       {
        _arrived = value;
        OnPropertyChanged("arrived");
       }
      }
     }
     
        private Nullable<System.DateTime> _date_import;
     public Nullable<System.DateTime> date_import 
     { 
      get
      {
       return _date_import;
      } 
      set
      {
       if(_date_import != value)
       {
        _date_import = value;
        OnPropertyChanged("date_import");
       }
      }
     }
     
    }
}
