//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Send: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _id_invoice;
     public decimal id_invoice 
     { 
      get
      {
       return _id_invoice;
      } 
      set
      {
       if(_id_invoice != value)
       {
        _id_invoice = value;
        OnPropertyChanged("id_invoice");
       }
      }
     }
     
        private decimal _id_merch;
     public decimal id_merch 
     { 
      get
      {
       return _id_merch;
      } 
      set
      {
       if(_id_merch != value)
       {
        _id_merch = value;
        OnPropertyChanged("id_merch");
       }
      }
     }
     
        private decimal _count;
     public decimal count 
     { 
      get
      {
       return _count;
      } 
      set
      {
       if(_count != value)
       {
        _count = value;
        OnPropertyChanged("count");
       }
      }
     }
     
        private decimal _price;
     public decimal price 
     { 
      get
      {
       return _price;
      } 
      set
      {
       if(_price != value)
       {
        _price = value;
        OnPropertyChanged("price");
       }
      }
     }
     
    
        private Invoice _Invoice;
     public virtual Invoice Invoice 
     { 
      get
      {
       return _Invoice;
      } 
      set
      {
       if(_Invoice != value)
       {
        _Invoice = value;
        OnPropertyChanged("Invoice");
       }
      }
     }
     
        private Merchandise _Merchandise;
     public virtual Merchandise Merchandise 
     { 
      get
      {
       return _Merchandise;
      } 
      set
      {
       if(_Merchandise != value)
       {
        _Merchandise = value;
        OnPropertyChanged("Merchandise");
       }
      }
     }
     
    }
}
