//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private string _name;
     public string name 
     { 
      get
      {
       return _name;
      } 
      set
      {
       if(_name != value)
       {
        _name = value;
        OnPropertyChanged("name");
       }
      }
     }
     
        private int _principal_id;
     public int principal_id 
     { 
      get
      {
       return _principal_id;
      } 
      set
      {
       if(_principal_id != value)
       {
        _principal_id = value;
        OnPropertyChanged("principal_id");
       }
      }
     }
     
        private int _diagram_id;
     public int diagram_id 
     { 
      get
      {
       return _diagram_id;
      } 
      set
      {
       if(_diagram_id != value)
       {
        _diagram_id = value;
        OnPropertyChanged("diagram_id");
       }
      }
     }
     
        private Nullable<int> _version;
     public Nullable<int> version 
     { 
      get
      {
       return _version;
      } 
      set
      {
       if(_version != value)
       {
        _version = value;
        OnPropertyChanged("version");
       }
      }
     }
     
        private byte[] _definition;
     public byte[] definition 
     { 
      get
      {
       return _definition;
      } 
      set
      {
       if(_definition != value)
       {
        _definition = value;
        OnPropertyChanged("definition");
       }
      }
     }
     
    }
}
