//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        public Users()
        {
            this.Order = new HashSet<Order>();
            this.Users_inv = new HashSet<Users_inv>();
        }
    
        private decimal _id_user;
     public decimal id_user 
     { 
      get
      {
       return _id_user;
      } 
      set
      {
       if(_id_user != value)
       {
        _id_user = value;
        OnPropertyChanged("id_user");
       }
      }
     }
     
        private string _family;
     public string family 
     { 
      get
      {
       return _family;
      } 
      set
      {
       if(_family != value)
       {
        _family = value;
        OnPropertyChanged("family");
       }
      }
     }
     
        private string _name;
     public string name 
     { 
      get
      {
       return _name;
      } 
      set
      {
       if(_name != value)
       {
        _name = value;
        OnPropertyChanged("name");
       }
      }
     }
     
        private string _patronymic;
     public string patronymic 
     { 
      get
      {
       return _patronymic;
      } 
      set
      {
       if(_patronymic != value)
       {
        _patronymic = value;
        OnPropertyChanged("patronymic");
       }
      }
     }
     
        private decimal _id_role;
     public decimal id_role 
     { 
      get
      {
       return _id_role;
      } 
      set
      {
       if(_id_role != value)
       {
        _id_role = value;
        OnPropertyChanged("id_role");
       }
      }
     }
     
    
        private ICollection<Order> _Order;
     public virtual ICollection<Order> Order 
     { 
      get
      {
       return _Order;
      } 
      set
      {
       if(_Order != value)
       {
        _Order = value;
        OnPropertyChanged("Order");
       }
      }
     }
     
        private Role _Role;
     public virtual Role Role 
     { 
      get
      {
       return _Role;
      } 
      set
      {
       if(_Role != value)
       {
        _Role = value;
        OnPropertyChanged("Role");
       }
      }
     }
     
        private User_Inf _User_Inf;
     public virtual User_Inf User_Inf 
     { 
      get
      {
       return _User_Inf;
      } 
      set
      {
       if(_User_Inf != value)
       {
        _User_Inf = value;
        OnPropertyChanged("User_Inf");
       }
      }
     }
     
        private ICollection<Users_inv> _Users_inv;
     public virtual ICollection<Users_inv> Users_inv 
     { 
      get
      {
       return _Users_inv;
      } 
      set
      {
       if(_Users_inv != value)
       {
        _Users_inv = value;
        OnPropertyChanged("Users_inv");
       }
      }
     }
     
    }
}
