//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Inf: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _id_user;
     public decimal id_user 
     { 
      get
      {
       return _id_user;
      } 
      set
      {
       if(_id_user != value)
       {
        _id_user = value;
        OnPropertyChanged("id_user");
       }
      }
     }
     
        private string _phone;
     public string phone 
     { 
      get
      {
       return _phone;
      } 
      set
      {
       if(_phone != value)
       {
        _phone = value;
        OnPropertyChanged("phone");
       }
      }
     }
     
        private string _adress;
     public string adress 
     { 
      get
      {
       return _adress;
      } 
      set
      {
       if(_adress != value)
       {
        _adress = value;
        OnPropertyChanged("adress");
       }
      }
     }
     
        private string _mail;
     public string mail 
     { 
      get
      {
       return _mail;
      } 
      set
      {
       if(_mail != value)
       {
        _mail = value;
        OnPropertyChanged("mail");
       }
      }
     }
     
        private string _notation;
     public string notation 
     { 
      get
      {
       return _notation;
      } 
      set
      {
       if(_notation != value)
       {
        _notation = value;
        OnPropertyChanged("notation");
       }
      }
     }
     
        private string _login;
     public string login 
     { 
      get
      {
       return _login;
      } 
      set
      {
       if(_login != value)
       {
        _login = value;
        OnPropertyChanged("login");
       }
      }
     }
     
        private string _password;
     public string password 
     { 
      get
      {
       return _password;
      } 
      set
      {
       if(_password != value)
       {
        _password = value;
        OnPropertyChanged("password");
       }
      }
     }
     
    
        private Users _Users;
     public virtual Users Users 
     { 
      get
      {
       return _Users;
      } 
      set
      {
       if(_Users != value)
       {
        _Users = value;
        OnPropertyChanged("Users");
       }
      }
     }
     
    }
}
