//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_inv: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _id_user;
     public decimal id_user 
     { 
      get
      {
       return _id_user;
      } 
      set
      {
       if(_id_user != value)
       {
        _id_user = value;
        OnPropertyChanged("id_user");
       }
      }
     }
     
        private decimal _id_worktype;
     public decimal id_worktype 
     { 
      get
      {
       return _id_worktype;
      } 
      set
      {
       if(_id_worktype != value)
       {
        _id_worktype = value;
        OnPropertyChanged("id_worktype");
       }
      }
     }
     
        private Nullable<System.DateTime> _datatime;
     public Nullable<System.DateTime> datatime 
     { 
      get
      {
       return _datatime;
      } 
      set
      {
       if(_datatime != value)
       {
        _datatime = value;
        OnPropertyChanged("datatime");
       }
      }
     }
     
        private decimal _id_invoice;
     public decimal id_invoice 
     { 
      get
      {
       return _id_invoice;
      } 
      set
      {
       if(_id_invoice != value)
       {
        _id_invoice = value;
        OnPropertyChanged("id_invoice");
       }
      }
     }
     
    
        private Invoice _Invoice;
     public virtual Invoice Invoice 
     { 
      get
      {
       return _Invoice;
      } 
      set
      {
       if(_Invoice != value)
       {
        _Invoice = value;
        OnPropertyChanged("Invoice");
       }
      }
     }
     
        private Users _Users;
     public virtual Users Users 
     { 
      get
      {
       return _Users;
      } 
      set
      {
       if(_Users != value)
       {
        _Users = value;
        OnPropertyChanged("Users");
       }
      }
     }
     
        private Worktype _Worktype;
     public virtual Worktype Worktype 
     { 
      get
      {
       return _Worktype;
      } 
      set
      {
       if(_Worktype != value)
       {
        _Worktype = value;
        OnPropertyChanged("Worktype");
       }
      }
     }
     
    }
}
