//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_merch: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        private decimal _Код_товара;
     public decimal Код_товара 
     { 
      get
      {
       return _Код_товара;
      } 
      set
      {
       if(_Код_товара != value)
       {
        _Код_товара = value;
        OnPropertyChanged("Код_товара");
       }
      }
     }
     
        private string _Наименование;
     public string Наименование 
     { 
      get
      {
       return _Наименование;
      } 
      set
      {
       if(_Наименование != value)
       {
        _Наименование = value;
        OnPropertyChanged("Наименование");
       }
      }
     }
     
        private string _Тип;
     public string Тип 
     { 
      get
      {
       return _Тип;
      } 
      set
      {
       if(_Тип != value)
       {
        _Тип = value;
        OnPropertyChanged("Тип");
       }
      }
     }
     
        private string _Описание;
     public string Описание 
     { 
      get
      {
       return _Описание;
      } 
      set
      {
       if(_Описание != value)
       {
        _Описание = value;
        OnPropertyChanged("Описание");
       }
      }
     }
     
        private decimal _Кол_во_заказано;
     public decimal Кол_во_заказано 
     { 
      get
      {
       return _Кол_во_заказано;
      } 
      set
      {
       if(_Кол_во_заказано != value)
       {
        _Кол_во_заказано = value;
        OnPropertyChanged("Кол_во_заказано");
       }
      }
     }
     
        private decimal _Кол_во_хранится;
     public decimal Кол_во_хранится 
     { 
      get
      {
       return _Кол_во_хранится;
      } 
      set
      {
       if(_Кол_во_хранится != value)
       {
        _Кол_во_хранится = value;
        OnPropertyChanged("Кол_во_хранится");
       }
      }
     }
     
        private decimal _Кол_во_продано;
     public decimal Кол_во_продано 
     { 
      get
      {
       return _Кол_во_продано;
      } 
      set
      {
       if(_Кол_во_продано != value)
       {
        _Кол_во_продано = value;
        OnPropertyChanged("Кол_во_продано");
       }
      }
     }
     
        private decimal _Кол_во_зарезервированно;
     public decimal Кол_во_зарезервированно 
     { 
      get
      {
       return _Кол_во_зарезервированно;
      } 
      set
      {
       if(_Кол_во_зарезервированно != value)
       {
        _Кол_во_зарезервированно = value;
        OnPropertyChanged("Кол_во_зарезервированно");
       }
      }
     }
     
        private decimal _C__партии;
     public decimal C__партии 
     { 
      get
      {
       return _C__партии;
      } 
      set
      {
       if(_C__партии != value)
       {
        _C__партии = value;
        OnPropertyChanged("C__партии");
       }
      }
     }
     
        private decimal _Наценка;
     public decimal Наценка 
     { 
      get
      {
       return _Наценка;
      } 
      set
      {
       if(_Наценка != value)
       {
        _Наценка = value;
        OnPropertyChanged("Наценка");
       }
      }
     }
     
        private decimal _Себестоимость;
     public decimal Себестоимость 
     { 
      get
      {
       return _Себестоимость;
      } 
      set
      {
       if(_Себестоимость != value)
       {
        _Себестоимость = value;
        OnPropertyChanged("Себестоимость");
       }
      }
     }
     
        private bool _Брибытие;
     public bool Брибытие 
     { 
      get
      {
       return _Брибытие;
      } 
      set
      {
       if(_Брибытие != value)
       {
        _Брибытие = value;
        OnPropertyChanged("Брибытие");
       }
      }
     }
     
    }
}
