//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worktype: System.ComponentModel.INotifyPropertyChanged
    
    {
    #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
        public Worktype()
        {
            this.Users_inv = new HashSet<Users_inv>();
        }
    
        private decimal _id_worktype;
     public decimal id_worktype 
     { 
      get
      {
       return _id_worktype;
      } 
      set
      {
       if(_id_worktype != value)
       {
        _id_worktype = value;
        OnPropertyChanged("id_worktype");
       }
      }
     }
     
        private string _name_work;
     public string name_work 
     { 
      get
      {
       return _name_work;
      } 
      set
      {
       if(_name_work != value)
       {
        _name_work = value;
        OnPropertyChanged("name_work");
       }
      }
     }
     
    
        private ICollection<Users_inv> _Users_inv;
     public virtual ICollection<Users_inv> Users_inv 
     { 
      get
      {
       return _Users_inv;
      } 
      set
      {
       if(_Users_inv != value)
       {
        _Users_inv = value;
        OnPropertyChanged("Users_inv");
       }
      }
     }
     
    }
}
